### ISSUE TITLE
Targeting Specific Font Files

### ISSUE THREAD

**Issue by archy-bold** [patrickhulce/fontmin-webpack#29]
The script works great, but has the unfortunate side effect of running on every font I use in my CSS including regular type-faces.

Is it possible to target only specific font files? ie only font-awesome and not other fonts.

**Comment by patrickhulce** [comment]
Thanks for filing @archy-bold! Not currently supported but it should be fairly simple to implement. Would you be interested in picking that up? :)

**Comment by archy-bold** [comment]
I'll add it to my to do list :)

Is there a usual webpack standard for that sort of thing? Using a regex to string/regex to match files?

**Comment by patrickhulce** [comment]
Hm not a standard perse but convention would suggest a regex option for the file names to match.

Maybe `allowedFilesRegex` and `skippedFilesRegex` for inclusive and exclusive matching?

**Comment by Moustachos** [comment]
@patrickhulce when you got time to check it, I made a pull request addressing this issue and #5 :)
