### ISSUE TITLE
Converting .ttf

### ISSUE THREAD

**Issue by TbIKoBKa** [patrickhulce/fontmin-webpack#50]
@patrickhulce 
After bundling i got just minified .ttf file. How to convert it to woff2?

I have such configuration:
```
module: {
    rules: [
        {
            test: /\.(woff|woff2|eot|ttf|otf)$/i,
            use:  [
                {
                    loader:  'file-loader',
                    options: {
                        name: 'assets/[hash:5].[ext]',
                    },
                },
            ],
        },
    ],
},

plugins: [
    new FontminPlugin({
        autodetect:        true,
        allowedFilesRegex: null,
        skippedFilesRegex: null,
    }),
],
```

**Comment by patrickhulce** [comment]
@TbIKoBKa do your other fonts have the same exact file name (minus extension) as the ttf version? See https://github.com/patrickhulce/fontmin-webpack#limitations

**Comment by TbIKoBKa** [comment]
@patrickhulce 
No, i have got just .ttf file and i want to convert it to another formats after bundling. Is it possible?

**Comment by patrickhulce** [comment]
> i want to convert it to another formats after bundling. Is it possible?

No, that's more involved than what this package does (requires modifying CSS font declarations, adding new assets to webpack, etc). Sorry!
