### ISSUE TITLE
fontmin-webpack does not recognize font if querystring in output filename

### ISSUE THREAD

**Issue by ArTiSTiX** [patrickhulce/fontmin-webpack#57]
For some reason, i use querystrings for cache bursting of assets, by appending something like an hash, allowing server to update files "in place".

This could notably done through `file-loader` by using:
```{
        loader: 'file-loader',
        options: {
          name: '[name].[ext]?[hash]',
        },
      }
```

Due to the hash being at the end of the filename, `fontmin-webpack` no longer detects the extension at the end of filename, and completely ignores the files (which are not minified then).

**Comment by patrickhulce** [comment]
a query string shouldn't appear in the filename itself, wouldn't it appear in the reference _to_ the file? or is that what you're saying breaks fontmin-webpack?

**Comment by ArTiSTiX** [comment]
@patrickhulce Yes, the querystring was referenced in the assets filenames, and was not handled by fontmin-webpack. All files having querystring were not treated through fontmin.
